name: thefood
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:

  authentication_repository:
    path: packages/authentication_repository

  form_inputs:
    path: packages/form_inputs

  cache:
    path: packages/cache

  navigator:
    path: packages/navigator

  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.1.1

  # Firebase
  firebase_auth: ^3.11.2
  firebase_messaging: ^13.1.0
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1

  # Style
  cupertino_icons: ^1.0.5
  kartal: ^2.5.1
  flutter_svg: ^1.1.6
  shimmer: ^2.0.0
  cached_network_image: ^3.2.2
  formz: ^0.4.1
  flutter_rating_bar: ^4.0.1
  lottie: ^2.0.0
  timeago: ^3.3.0
  flutter_native_splash: ^2.2.16
  validators: ^3.0.0

  # Navigation
  go_router: ^5.1.6

  # Network
  dio: ^4.0.6
  url_launcher: ^6.1.6
  flutter_offline: ^2.1.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11




  # google_mobile_ads: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  hive_generator: ^2.0.0
  json_annotation: ^4.7.0
  flutter_launcher_icons: "^0.11.0"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo.jpg
  color_dark: "#121212"
  image_dark: assets/images/app_logo.jpg
  branding_dark: assets/images/app_logo.jpg

  android_12:
    image: assets/images/app_logo.jpg
    icon_background_color: "#ffffff"
    image_dark: assets/images/app_logo.jpg
    icon_background_color_dark: "#121212"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_logo.jpg"
    background_color: "#000000"
    theme_color: "#000000"


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
