import 'package:thefood/models/meals.dart';

class MealList {
  final meals = Meals(
    idMeal: '',
    strMeal: '',
    strMealThumb: '',
    strArea: '',
    strCategory: '',
    strInstructions: '',
    strYoutube: '',
    strSource: '',
    strTags: '',
    strImageSource: '',
    strIngredient1: '',
    strIngredient2: '',
    strIngredient3: '',
    strIngredient4: '',
    strIngredient5: '',
    strIngredient6: '',
    strIngredient7: '',
    strIngredient8: '',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '',
    strMeasure2: '',
    strMeasure3: '',
    strMeasure4: '',
    strMeasure5: '',
    strMeasure6: '',
    strMeasure7: '',
    strMeasure8: '',
    strMeasure9: '',
    strMeasure10: '',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
  );
}

class IngredientList {
  final ingredienList = [
    Meals().strIngredient1,
    Meals().strIngredient2,
    Meals().strIngredient3,
    Meals().strIngredient4,
    Meals().strIngredient5,
    Meals().strIngredient6,
    Meals().strIngredient7,
    Meals().strIngredient8,
    Meals().strIngredient9,
    Meals().strIngredient10,
    Meals().strIngredient11,
    Meals().strIngredient12,
    Meals().strIngredient13,
    Meals().strIngredient14,
    Meals().strIngredient15,
    Meals().strIngredient16,
    Meals().strIngredient17,
    Meals().strIngredient18,
    Meals().strIngredient19,
    Meals().strIngredient20,
  ];
}

class MeasureList {
  final measureList = [
    Meals().strMeasure1,
    Meals().strMeasure2,
    Meals().strMeasure3,
    Meals().strMeasure4,
    Meals().strMeasure5,
    Meals().strMeasure6,
    Meals().strMeasure7,
    Meals().strMeasure8,
    Meals().strMeasure9,
    Meals().strMeasure10,
    Meals().strMeasure11,
    Meals().strMeasure12,
    Meals().strMeasure13,
    Meals().strMeasure14,
    Meals().strMeasure15,
    Meals().strMeasure16,
    Meals().strMeasure17,
    Meals().strMeasure18,
    Meals().strMeasure19,
    Meals().strMeasure20,
  ];
}
