Map<String, String> countryFlagMap = {
  'American': 'https://www.themealdb.com/images/icons/flags/big/64/us.png',
  'British': 'https://www.themealdb.com/images/icons/flags/big/64/gb.png',
  'Canadian': 'https://www.themealdb.com/images/icons/flags/big/64/ca.png',
  'Chinese': 'https://www.themealdb.com/images/icons/flags/big/64/cn.png',
  'Croatian': 'https://www.themealdb.com/images/icons/flags/big/64/hr.png',
  'Dutch': 'https://www.themealdb.com/images/icons/flags/big/64/nl.png',
  'Egyptian': 'https://www.themealdb.com/images/icons/flags/big/64/eg.png',
  'French': 'https://www.themealdb.com/images/icons/flags/big/64/fr.png',
  'Greek': 'https://www.themealdb.com/images/icons/flags/big/64/gr.png',
  'Indian': 'https://www.themealdb.com/images/icons/flags/big/64/in.png',
  'Irish': 'https://www.themealdb.com/images/icons/flags/big/64/ie.png',
  'Italian': 'https://www.themealdb.com/images/icons/flags/big/64/it.png',
  'Jamaican': 'https://www.themealdb.com/images/icons/flags/big/64/jm.png',
  'Japanese': 'https://www.themealdb.com/images/icons/flags/big/64/jp.png',
  'Kenyan': 'https://www.themealdb.com/images/icons/flags/big/64/ke.png',
  'Malaysian': 'https://www.themealdb.com/images/icons/flags/big/64/my.png',
  'Mexican': 'https://www.themealdb.com/images/icons/flags/big/64/mx.png',
  'Moroccan': 'https://www.themealdb.com/images/icons/flags/big/64/ma.png',
  'Polish': 'https://www.themealdb.com/images/icons/flags/big/64/pl.png',
  'Portuguese': 'https://www.themealdb.com/images/icons/flags/big/64/pt.png',
  'Russian': 'https://www.themealdb.com/images/icons/flags/big/64/ru.png',
  'Spanish': 'https://www.themealdb.com/images/icons/flags/big/64/es.png',
  'Thai': 'https://www.themealdb.com/images/icons/flags/big/64/th.png',
  'Tunisian': 'https://www.themealdb.com/images/icons/flags/big/64/tn.png',
  'Turkish': 'https://www.themealdb.com/images/icons/flags/big/64/tr.png',
  'Unknown': 'https://cdn.icon-icons.com/icons2/45/PNG/64/unknown_flags_flag_9091.png',
  'Vietnamese': 'https://www.themealdb.com/images/icons/flags/big/64/vn.png',
};

Map<String, String> countryFlags = {
  'America': 'https://www.themealdb.com/images/icons/flags/big/64/us.png',
  'United Kingdom': 'https://www.themealdb.com/images/icons/flags/big/64/gb.png',
  'Canada': 'https://www.themealdb.com/images/icons/flags/big/64/ca.png',
  'China': 'https://www.themealdb.com/images/icons/flags/big/64/cn.png',
  'Croatia': 'https://www.themealdb.com/images/icons/flags/big/64/hr.png',
  'Netherlands': 'https://www.themealdb.com/images/icons/flags/big/64/nl.png',
  'Egypt': 'https://www.themealdb.com/images/icons/flags/big/64/eg.png',
  'France': 'https://www.themealdb.com/images/icons/flags/big/64/fr.png',
  'Greece': 'https://www.themealdb.com/images/icons/flags/big/64/gr.png',
  'India': 'https://www.themealdb.com/images/icons/flags/big/64/in.png',
  'Ireland': 'https://www.themealdb.com/images/icons/flags/big/64/ie.png',
  'Italy': 'https://www.themealdb.com/images/icons/flags/big/64/it.png',
  'Jameica': 'https://www.themealdb.com/images/icons/flags/big/64/jm.png',
  'Japan': 'https://www.themealdb.com/images/icons/flags/big/64/jp.png',
  'Kenya': 'https://www.themealdb.com/images/icons/flags/big/64/ke.png',
  'Malaysia': 'https://www.themealdb.com/images/icons/flags/big/64/my.png',
  'Mexica': 'https://www.themealdb.com/images/icons/flags/big/64/mx.png',
  'Morocco': 'https://www.themealdb.com/images/icons/flags/big/64/ma.png',
  'Poland': 'https://www.themealdb.com/images/icons/flags/big/64/pl.png',
  'Portugal': 'https://www.themealdb.com/images/icons/flags/big/64/pt.png',
  'Russia': 'https://www.themealdb.com/images/icons/flags/big/64/ru.png',
  'Spain': 'https://www.themealdb.com/images/icons/flags/big/64/es.png',
  'Thailand': 'https://www.themealdb.com/images/icons/flags/big/64/th.png',
  'Tunisia': 'https://www.themealdb.com/images/icons/flags/big/64/tn.png',
  'Turkey': 'https://www.themealdb.com/images/icons/flags/big/64/tr.png',
  'Unknown': 'https://cdn.icon-icons.com/icons2/45/PNG/64/unknown_flags_flag_9091.png',
  'Vietnam': 'https://www.themealdb.com/images/icons/flags/big/64/vn.png',
};
